FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run db:generate
RUN npm run build --workspace apps/api

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app /app
EXPOSE 4000
CMD ["npm","run","dev","--workspace","apps/api"]
